-- =============================================================================
-- Workflow template seeding moved to supabase/seed.sql (UUID: a91887dd-edbb-4e75-aa76-217977848177)
-- This migration is intentionally left empty after refactor.
-- =============================================================================
